on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy to Firebase Hosting
    steps:
      - uses: "actions/checkout@v4"
      - uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
      - name: Install modules
        run: npm install
      - name: Create .env file
        run: |
          # echo "${{ secrets.VITE_FIREBASE_API_KEY }}" >> .env
          # echo "${{ secrets.VITE_FIREBASE_APP_ID }}" >> .env
          # echo "${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" >> .env
          # echo "${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}" >> .env
          # echo "${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "${{ secrets.VITE_FIREBASE_PROJECT_ID }}" > .env
          # echo "${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}" >> .env
      - name: Build application
        run: npm run build
      - name: Install `firebase-tools` module globally
        run: npm install -g firebase-tools@13.16.0
      - name: Deploy
        run: firebase deploy
